-- CREATE TABLE VARIABLE . VARIABLE AS SELECT VARIABLE FROM VARIABLE ; 
CREATE TABLE "NATURE" . "ANIMALS" AS SELECT TIGERS FROM JUNGLE ; 
-- CREATE TABLE VARIABLE . VARIABLE AS SELECT VARIABLE FROM VARIABLE ; 
CREATE TABLE "
NATURE" . "ANIMALS" AS SELECT TIGERS FROM JUNGLE ; 
-- CREATE TABLE VARIABLE . VARIABLE AS SELECT VARIABLE FROM VARIABLE ; 
CREATE TABLE "NATURE
" . "ANIMALS" AS SELECT TIGERS FROM JUNGLE ; 
-- CREATE TABLE VARIABLE . VARIABLE AS SELECT VARIABLE FROM VARIABLE ; 
CREATE TABLE "NATURE" . "ANIMALS" AS SELECT TIGERS FROM JUNGLE ; 
-- CREATE TABLE VARIABLE . VARIABLE AS SELECT VARIABLE FROM VARIABLE ; 
CREATE TABLE "NAT URE" . "ANIMALS " AS SELECT TIGERS FROM JUNGLE ; 
-- CREATE TABLE VARIABLE . VARIABLE AS SELECT VARIABLE FROM VARIABLE ; 
CREATE TABLE " NATURE" . "ANI MALS" AS SELECT TIGERS FROM JUNGLE ; 
-- CREATE TABLE VARIABLE . VARIABLE AS SELECT VARIABLE FROM VARIABLE ; 
CREATE TABLE "CREATE" . "ANIMALS" AS SELECT TIGERS FROM JUNGLE ; 
-- VARIABLE CREATE TABLE VARIABLE . VARIABLE AS SELECT VARIABLE FROM VARIABLE ; 
"" CREATE TABLE "NATURE" . "ANIMALS" AS SELECT TIGERS FROM JUNGLE ; 
-- VARIABLE 
"AA" 
