WORDS WORDS /*   THIS IS
    A MULTILINE
          COMMENT */ WORDS WORDS

WORDS WORDS 
/*   THIS IS
    A MULTILINE
          COMMENT */ WORDS WORDS


WORDS WORDS /*
   THIS IS
    A MULTILINE
          COMMENT */ WORDS WORDS


WORDS WORDS /*   THIS IS
    A MULTILINE
          COMMENT */
 WORDS WORDS



WORDS WORDS /*   THIS IS
    A MULTILINE
          COMMENT */